Update All Codes.yml

diff --git a/.github/workflows/All Codes.yml b/.github/workflows/All Codes.yml
--- a/.github/workflows/All Codes.yml
+++ b/.github/workflows/All Codes.yml
@@ -33,3 +33,12 @@ jobs:
         SF_SANDBOX_USERNAME: ${{ secrets.SF_SANDBOX_USERNAME }}
       run: |
         sfdx force:source:deploy -p force-app -u $SF_SANDBOX_USERNAME
+
+        # Check if the deployment succeeded
+        if [ $? -eq 0 ]; then
+          echo "Deployment succeeded!"
+        else
+          echo "Deployment failed. Check the logs below:"
+          cat deploy.log
+          exit 1
+        fi
